# Generated by Django 2.0.3 on 2018-03-24 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_post_score_voted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_score',
            name='downvoted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_score_downvoted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post_score',
            name='upvoted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_score_upvoted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
